blog/urls.py
# -*- coding:utf-8 -*-
"""myProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from blog import views

urlpatterns = [
    #url(r'^admin/', include(admin.site.urls)),
	#url(r'^$', views.home_page, name = 'home'),#создали путь к home_page
	url(r'^$', views.index, name = 'blog'), #main page of the blog app
    url(r'^categories', views.categories, name='categories'),
    url(r'^category/(?P<categoryslug>.*)/$', 'blog.views.category'),
    url(r'^posts/(?P<postslug>.*)/$', 'blog.views.view'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^login/$', views.user_login, name = 'login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name = 'logout'),
    url(r"^add_comment/(?P<postslug>.*)/$", "blog.views.add_comment"),
    url(r"^month/(\d+)/(\d+)/$", "blog.views.month"),
    url(r'^pages/(?P<pageslug>.*)/$', 'blog.views.page'),
    url(r'^goto/$', 'blog.views.track_url', name='goto'),


]

myProject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^blog/', include('blog.urls')),
    url(r'^cat/', include('blog.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name="homepage"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from utils import helpers

class Category(models.Model):
    name = models.CharField(max_length = 128, unique = True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

BLOG_ITEM_STATUS = (
    ('0', 'Draft'),
    ('1', 'Published'),
    ('2', 'Not Published'),
)

ITEM_STATUS_PUBLISHED = 1
ITEM_STATUS_HIDDEN = 2
ITEM_STATUS_CHOICES = (
    (ITEM_STATUS_PUBLISHED, "Published"),
    (ITEM_STATUS_HIDDEN, "Hidden"),
)

class Post(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length = 128)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    status = models.CharField(max_length=1, choices=BLOG_ITEM_STATUS, default='0')
    url = models.URLField()
    views = models.IntegerField(default = 0)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank = True)
    picture = models.ImageField(upload_to = 'profile_images', blank = True)

    def __str__(self):
        return self.user.username

class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(User)
    body = models.TextField()
    post = models.ForeignKey(Post)

    def __str__(self):
        return str("%s: %s" % (self.post, self.body[:60]))

def get_blog_file_name(instance, filename):
    return helpers.get_file_filename(instance, filename, "blog")


class Slider(models.Model):
    status = models.IntegerField(choices=ITEM_STATUS_CHOICES, default=ITEM_STATUS_PUBLISHED)
    title = models.CharField(max_length=32)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return u"{}".format(self.title)

class Slide(models.Model):
    status = models.IntegerField(choices=ITEM_STATUS_CHOICES, default=ITEM_STATUS_PUBLISHED)
    title = models.CharField(max_length=32)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(max_length=1024, null=True, blank=True, upload_to=get_blog_file_name)
    related_slider = models.ForeignKey(Slider)

    def __str__(self):
        return u"{}".format(self.title)


class Page(models.Model):
    status = models.IntegerField(choices=ITEM_STATUS_CHOICES, default=ITEM_STATUS_PUBLISHED)
    title = models.CharField(max_length=32)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    # content = RichTextField()
    #widgets = models.ManyToManyField(Widget, null=True, blank=True)
    featured_image = models.ImageField(max_length=1024, null=True, blank=True, upload_to=get_blog_file_name)
    related_slider = models.ForeignKey(Slider, null=True, blank=True)

    def __str__(self):
        return u"{}".format(self.title)



# Create your models here.

blog/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from blog.models import Category, Post, UserProfile, Comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ["post"]

blog/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse
import datetime
from blog.models import Category, Post, Comment, Page
from django.views.generic import TemplateView
from blog.forms import UserForm, UserProfileForm, CommentForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.template.context_processors import csrf
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
import time
from calendar import month_name

class MyStructure(object):
	"""docstring for """
	pass


def home_page(request):
	hel='<html><title>Blog lists</title>Hello My PythonBlog <br> "You must be joking!" I can hear you say.</html>'
	return HttpResponse(hel)

def index(request):
	#c = MyStructure()
	#c.company = 'Cool Star'
	#c.title = 'Galina Titova Blog'
	#c.author_name = 'Jhon Smith'
	#c.pub_date = datetime.datetime.now()
	#c.article_list = [{'title': "Title1", 'text': "Text1"}, {'title': "Title2", 'text': "Text2"}, {'title': "Title3", 'text': "Text3"}, {'title': "Title4", 'text': "Text4"}]
	#c.boldmessage = "Вы можете изменить значение переменной используя фильтры. Фильтры выглядят таким образом: {{ name|lower }}. Это выведет значение переменной {{ name }} после применения фильтра lower к нему, который преобразует значение в нижний регистр. Используйте символ (|) для применения фильтра. I am bold font from the context"
	#c.text = 'Вы можете изменить значение переменной используя фильтры. Фильтры выглядят таким образом: {{ name|lower }}. Это выведет значение переменной {{ name }} после применения фильтра lower к нему, который преобразует значение в нижний регистр. Используйте символ (|) для применения фильтра. I am bold font from the context Можно использовать “цепочку” фильтров. Вывод одного фильтра используется для другого. {{ text|escape|linebreaks }} обычно применяется для экранирования текста, и замены переноса строки тегами <p>.'
	#return render(request, 'blog/index.html', c.__dict__)

	#posts_list = Post.objects.order_by('title')

	category_list = Category.objects.order_by('name')
	posts = Post.objects.all().order_by("-created")
	paginator = Paginator(posts, 2)
	try: page = int(request.GET.get("page", '1'))
	except ValueError: page = 1
	try:
		posts = paginator.page(page)
	except (InvalidPage, EmptyPage):
		posts = paginator.page(paginator.num_pages)
	context_dict = {'categories_list':category_list, 'posts':posts, 'months':mkmonth_lst(),  'archive':True }
	return render_to_response("blog/index.html", context_dict)

#class AboutView(TemplateView):
	#template_name = "about.html"

def categories(request):
		category_list = Category.objects.order_by('name')

		context_dict = {'category_list': category_list}
		return render(request, 'blog/cat.html', context_dict)

def category(reqeust, categoryslug):
	name = Category.objects.get(slug = categoryslug)
	posts = Post.objects.filter(category = name)
	context = {'posts': posts}
	return render_to_response('blog/singlecategory.html', context)

def view(request, postslug):
	post = Post.objects.get(slug = postslug)
	comments = Comment.objects.filter(post=post)
	context = {'post': post, "comments":comments,"form":CommentForm(), "user":request.user}
	context.update(csrf(request))
	return render_to_response('blog/singlepost.html', context)

def register(request):
	registered = False
	if request.method == 'POST':
		user_form = UserForm(data = request.POST)
		profile_form = UserProfileForm(data = request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit = False)
			profile.user = user
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
			profile.save()
			registered = True
		else:
			print (user_form.errors, profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()
	return render(request, 'blog/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate (username=username, password=password)
		if user:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/blog/')
			else:
				return HttpResponse("Your Blog account is disabled.")
		else:
			print ("Invalid login details: {0}, {1}".format(username, password))
			return HttpResponse("Invalid login details supplied.")
	else:
		return render(request, 'blog/login.html', {})

@login_required
def restricted(request):
	return HttpResponse("Since you're logged in, you can see this text!")

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect('/blog/')

def add_comment(request, postslug):
    p = request.POST
    if p["body"]:
        author = request.user
        comment = Comment(post=Post.objects.get(slug=postslug))
        cf = CommentForm(p, instance=comment)

        cf.fields["author"].required = False
        comment = cf.save(commit=False)
        comment.author = author
        comment.save()
    return HttpResponseRedirect('/blog/')

def mkmonth_lst():
    """Make a list of months to show archive links."""

    if not Post.objects.count(): return []

    # set up vars
    year, month = time.localtime()[:2]
    first = Post.objects.order_by("created")[0]
    fyear = first.created.year
    fmonth = first.created.month
    months = []

    # loop over years and months
    for y in range(year, fyear-1, -1):
        start, end = 12, 0
        if y == year: start = month
        if y == fyear: end = fmonth-1

        for m in range(start, end, -1):
            months.append((y, m, month_name[m]))
    return months

def month(request, year, month):
    """Monthly archive."""

    posts = Post.objects.filter(created__year=year, created__month=month)

    paginator = Paginator(posts, 2)

    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render_to_response("blog/list.html", dict(posts=posts, user=request.user, months=mkmonth_lst(),  archive=True))

def page(request, pageslug):
    page = Page.objects.get(slug=pageslug)
    context = {'page': page, "user":request.user}
    return render_to_response('blog/page.html', context)

def track_url(request):
    post_id = None
    url = '/blog/'
    if request.method == 'GET':
        if 'post_id' in request.GET:
            post_id = request.GET['post_id']
            try:
                post = Post.objects.get(id=post_id)
                post.views = post.views + 1
                post.save()
                url = post.url
            except:
                pass

    return redirect(url)
# Create your views here.

templates/blog/_slider.html
<div id="application-bootstrap-carousel" class="carousel slide" data-ride="carousel">
    {# Indicators #}
    <ol class="carousel-indicators">
        {% for slide in slider.slide_set.all %}
            <li data-target="#slide-{{ forloop.counter0 }}" data-slide-to="{{ forloop.counter0 }}"
                    {% if forloop.counter0 == 0 %} class="active" {% endif %}></li>
        {% endfor %}
    </ol>

    {# Wrapper for slides #}
    <div class="carousel-inner">
        {% for slide in slider.slide_set.all %}
            <div {% if forloop.counter0 == 0 %} class="item active" {% else %} class="item" {% endif %}>
                <img src="/media/{{ slide.image }}"
                     alt="{{ slide.title }}" title="{{ slide.title }}" />
                <div class="carousel-caption">
                    <h3>{{ slide.title }}</h3>
                    <p>{{ slide.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    {# Controlls #}
    <a class="left carousel-control" href="#application-bootstrap-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#application-bootstrap-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

templates/blog/cat.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} {{ block.super }} - SECTION NAME {% endblock %}

{% block content %}
<h1>Categories</h1>
<h2>{{ title }}</h2>

{% for cat in category_list %}
	<div>
		<h2><a href="#">
		{{ cat.name }}
		</a></h2>

		</div>
	{% endfor %}
{% endblock %}

templates/blog/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
        <li>
        <a href="/blog/category/{{ c.slug }}/">
        {{ c.name }}
        </a></li>
    {% endfor %}

{% else %}
    <li> <strong >There are no category present.</strong></li>

    </ul>
{% endif %}

templates/blog/index.html
{% extends "base.html" %}
{% block title %} {{ block.super }} - main page {% endblock %}
{% load staticfiles %}
{% block content %}
<a href="/blog/register/">Register Here</a>
<a href="/blog/login/">Sign in</a>
{% if user.is_authenticated %}
<h2>Blog says HELLO {{ user.username }}!</h2>
{% else %}
<h2>Blog says HELLO guest!</h2>
{% endif %}

<h1>Blog CATEGORIES{{ title }}</h1>
	{% if categories_list %}
    <ul>
      {% for category in categories_list %}
        <li>{{ category.name }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <strong>There are no categories present.</strong>
  {% endif %}
<h1>Blog POST-LIST{{ title }}</h1>
  {% if posts_list %}
    <div id = "postslist">
				{% for post in posts_list %}
          <p><a href="/blog/posts/{{ post.slug }}/">{{ post.title }}</a></p>
        {% endfor %}
    </div>
  {% else %}
    <strong>There are no posts present.</strong>
  {% endif %}
<!--
<h2>{{ title | upper }}</h2>
<h2> {{ title|lower }}</h2>

<p><b>{{ boldmessage }}</b></p>
<img src="{% static 'images/images.png' %}">
<p>{{ text|escape|linebreaks }}</p>

{{ boldmessage|truncatewords:30 }}
<p><b>{{ boldmessage|addslashes }}</b></p>

{{ datet|date:"SHORT_DATE_FORMAT" }}

{% lorem 4 p random %}--><!-- 4 рандомных абзаца -->
<!--{% for article in article_list %}
	<div>
		<h2><a href="#">
		{{ article.title }}
		</a></h2>
	 		{% lorem 1 p random %}
		</div>
	{% endfor %}-->

{% endblock %}

templates/blog/lastnews.html
<div id = "news">
<h4>Последние статьи</h4>
<ul class="links">
	{% for post in last3news %}
       <li><a href="/blog/posts/{{ post.slug }}/">{{ post.title }}</a></li>
    {% endfor %}

</ul>
</div>

templates/blog/list.html
{% extends "base.html" %}
{% block title %} {{ block.super }} - main page {% endblock %}
{% load staticfiles %}
{% block sidebar %}
    <style type="text/css">
        #sidebar { float: right; border: 1px dotted #ccc; padding: 4px; }
    </style>
    <div id="sidebar">
        Monthly Archive<br />
        {% for month in months %}
            <a href="/blog/month/{{ month.0 }}/{{month.1 }}/">{{ month.2 }}</a> <br />
        {% endfor %}
    </div>
{% endblock %}
{% block content %}
<a href="/blog/register/">Register Here</a>
<a href="/blog/login/">Sign in</a>
{% if user.is_authenticated %}
<h2>Blog says HELLO {{ user.username }}!</h2>
{% else %}
<h2>Blog says HELLO guest!</h2>
{% endif %}

<h1>Blog CATEGORIES{{ title }}</h1>
	{% if categories_list %}
    <ul>
      {% for category in categories_list %}
        <li>{{ category.name }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <strong>There are no categories present.</strong>
  {% endif %}
<h1>Blog POST-LIST{{ title }}</h1>

    <div id = "postslist">
				{% for post in posts %}
          <p><a href="/blog/posts/{{ post.slug }}/">{{ post.title }}</a></p>
        {% endfor %}

				<!-- Next/Prev page links  -->
				{% if posts.object_list and posts.paginator.num_pages > 1 %}
	        <div class="pagination" style="margin-top: 20px; margin-left: -20px; ">
	            <span class="step-links">
	                {% if posts.has_previous %}
	                    <a href= "?page={{ posts.previous_page_number }}">newer entries &lt;&lt; </a>
	                {% endif %}

	                <span class="current">
	                    &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
	                </span>

	                {% if posts.has_next %}
	                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; older entries</a>
	                {% endif %}
	            </span>
	        </div>
	       {% endif %}
    </div>
{% endblock %}

templates/blog/login.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} {{ block.super }} - SECTION NAME {% endblock %}

{% block content %}
  <h2>Login to Blog</h2>
  <form id = "login_form" method="post" action="/blog/login/" enctype="multipart/form-data">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />
    <input type="submit" name="submit" value="REGISTER">
  </form>
{% endblock %}

templates/blog/logout.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} {{ block.super }} - SECTION NAME {% endblock %}
{% block content %}
  <h2>Logout from Blog</h2>
  {% if user.is_authenticated %}
<a href="/blog/logout/">Logout</a><br />
{% else %}
<a href="/blog/register/">Register Here</a><br />
<a href="/blog/login/">Login</a><br />
{% endif %}

<a href="/blog/about/">About</a><br/>
<a href="/blog/add_category/">Add a New Category</a><br />
{% endblock %}

templates/blog/page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
        <div class="col-md-12">
            {% if page.featured_image %}
                <img src="{{ page.featured_image }}" title="{{ page.title }}" />
            {% endif %}
            <h1>{{ page.title }}</h1>
            <p>
                {{ page.content|safe }}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" id="slider1">
            {% if page.related_slider %}
                {% include "blog/_slider.html" with slider=page.related_slider %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/blog/register.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} {{ block.super }} - SECTION NAME {% endblock %}

{% block content %}
  {% if registered %}
    <strong>Thank you for registration!</strong>
    <a href = "/blog/">Return to the homepage.</a></br>
  {% else %}
    <strong>Register here!</strong></br>
  <form id = "user_form" method="post" action="/blog/register/" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="submit" value="REGISTER">
  </form>
  {% endif %}

{% endblock %}

templates/blog/singlecategory.html
{% extends "base.html" %}
{% block content %}
        <div id="categorieslist">
                <h2>Category {{ posts.0.category }}</h2>
                {% for post in posts %}
         <p><a href="/blog/posts/{{ post.slug }}/">{{ post.title }}</a></p>
                {% endfor %}
        </div>
{% endblock %}

templates/blog/singlepost.html
{% extends "base.html" %}
{% block content %}
        <div id="singlepost">
                <h2>{{ post.title }}</h2>
                <p>{% autoescape off %}{{ post.body }}{% endautoescape %}</p>
                <div>
                  <a href="{% url 'goto' %}?post_id={{post.id}}">{{ post.title }}</a>
                  {% if post.views > 1 %} ({{ post.views }} views)
                  {% elif post.views == 1 %} ({{ post.views }} view)
                  {% endif %}
                </div>
                <!-- Comments  -->
                {% if comments %}
                <p>Comments:</p>
                {% endif %}
                {% for comment in comments %}
                  <div class="comment">
                      <div class="time">{{ comment.created }} | {{ comment.author }}</div>
                      <div class="body">{{ comment.body|linebreaks }}</div>
                  </div>
                {% endfor %}
                {% if user.is_authenticated %}
                    <div id="addc">Add a comment</div>
                    <!-- Comment form  -->
                    <form action="/blog/add_comment/{{ post.slug }}/" method="POST">{% csrf_token %}
                      <!-- защита против CSRF атак -->
                      <div id="cform">
                   			<p>{{ form.body }}</p>
                			</div>
          			      <div id="submit"><input type="submit" value="Submit"></div>
    			          </form>
			          {% endif %}
                <p>Category: <a href="/blog/categories/{{ post.category.slug }}/">{{ post.category }}</a></p>
        </div>
{% endblock %}